
spring:
  application:
    name: "SpringsecurityMongoImplementation"
  data:
    mongodb:
#      uri: mongodb://root:rootPassXXX@localhost:9000/core?retryWrites=true&w=majority
      host: localhost
      port: 27017
      database: "core"
#      username: "root"
#      password: "rootPassXXX"
      auto-index-creation: true
#  security:
#    user:
#      password: "12345"
#      name: user1
server:
  port: 8080

security:
  jwt:
    private: "15a560ea3f3c128319c2510ba20aaea5540ed6498b16786b4822f3c85f05ef24"
    user:
      generator: "AUTHJWT-BACKEND"

#  SecretKeyJWT 15a560ea3f3c128319c2510ba20aaea5540ed6498b16786b4822f3c85f05ef24